data_root : data

data_injuction : 
  root_dir : data/data_injection
  source_url : https://github.com/krishnaik06/datasets/raw/refs/heads/main/winequality-data.zip
  output_zip : data/data_injection/data.zip
  output : data/data_injection

data_validation :
  root_dir : data/data_validation
  injuction_data_csv : data/data_injection/winequality-red.csv
  output_report : data/data_validation/script.txt

data_transformation :
  input : data/data_injection/winequality-red.csv
  output : data/data_transformation
  
model_train :
  root_dir : models
  train_data : data/data_transformation/train.csv
  test_data : data/data_transformation/test.csv
  model_out : models/model.pkl

model_evaluation :
  root_dir : data/model_evaluation
  model_path : models/model.pkl
  test_data : data/data_transformation/test.csv
  output_file : data/model_evaluation/metrices.json

